apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-repo
  namespace: monitoring
spec:
  url: https://prometheus-community.github.io/helm-charts
  interval: 1h0m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 51.2.0 # Укажите нужную версию
      sourceRef:
        kind: HelmRepository
        name: prometheus-repo
      interval: 5m
  values:
    prometheus:
      prometheusSpec:
        retention: 10d
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 1Gi
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 1Gi
    grafana:
      enabled: false # Если Grafana уже задеплоена отдельно
